version: "3.8"
services:
  # Application
  app:
    build:
      context: ./docker/services/app
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
  # Web Server
  web:
    build:
      context: ./docker/services/web
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/services/web/conf.d/:/etc/nginx/conf.d/
      - ./docker/services/web/ssl/:/etc/nginx/ssl/
    ports:
      - "81:80"
      - "443:443"
  # Database
  database:
    platform: linux/x86_64
    image: mysql:8.0.25
    restart: unless-stopped
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "127.0.0.1:3309:3306"
    command:
      - --sort_buffer_size=402653184
  # Caching
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./docker/volumes/redis:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "127.0.0.1:6379:6379"
